---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == 'RedHat' or
      ansible_os_family == 'Debian'

- name: Create YUM repo file
  yum_repository:
    name: glusterfs
    description: GlusterFS YUM repo
    baseurl: "{{ glusterfs_client_yumrepo_url }}"
    gpgcheck: no
  when: >
    ansible_os_family == 'RedHat'
  tags:
    - glusterfs_client_pkg

- name: Add APT repo key
  apt_key:
    url: "{{ glusterfs_client_apt_key }}"
  when: >
    glusterfs_client_apt_key | length > 0 and
    ansible_os_family == 'Debian' and
    ansible_distribution == 'Debian'
  tags:
    - glusterfs_client_pkg

- name: Create APT repo file
  apt_repository:
    repo: "{{ glusterfs_client_apt_url }}"
  when: >
    ansible_os_family == 'Debian'
  tags:
    - glusterfs_client_pkg

- name: Install GlusterFS client
  package:
    name: "{{ glusterfs_client_pkg }}"
  tags:
    - glusterfs_client_pkg

- name: Create mount points
  file:
    path: "{{ item.dir | default(glusterfs_client_dir) }}"
    owner: "{{ item.dir_owner | default(glusterfs_client_dir_owner) }}"
    group: "{{ item.dir_group | default(glusterfs_client_dir_group) }}"
    mode: "{{ item.dir_mode | default(glusterfs_client_dir_mode) }}"
    state: directory
  with_items: "{{ glusterfs_client_volumes }}"
  tags:
    - glusterfs_client_volume

- name: Mount volumes
  mount:
    path: "{{ item.dir | default(glusterfs_client_dir) }}"
    src: "{{ item.servers[0] }}:/{{ item.name }}"
    fstype: glusterfs
    opts: "{{
        (
          'backupvolfile-server=' ~ (
            item.servers[1:] | join(':')
          )
        )
          if item.servers | length > 0
          else
        ''
      }}{{
        ','
          if item.servers | length > 1
          else
        '' }}{{ item.opts | default(glusterfs_client_volume_default_opts) }}"
    state: "{{ item.state | default('mounted') }}"
  with_items: "{{ glusterfs_client_volumes }}"
  tags:
    - glusterfs_client_volume
